package com.minorproject.docprocessor.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

@Service
public class PdfReportService {

    public byte[] generatePdfReport(String fileName, String summary, int originalWords, int summaryWords, int compression) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, out);

            document.open();

            // 1. Title
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 24, Color.BLUE);
            Paragraph title = new Paragraph("ADRP Analysis Report", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            document.add(title);

            // 2. File Metadata
            Font metaFont = FontFactory.getFont(FontFactory.HELVETICA, 12, Color.DARK_GRAY);
            document.add(new Paragraph("File Name: " + fileName, metaFont));
            document.add(new Paragraph("Processed Date: " + new java.util.Date(), metaFont));
            document.add(new Paragraph("------------------------------------------------", metaFont));

            // 3. Statistics Section
            Font statsHeader = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Color.BLACK);
            document.add(new Paragraph("\nProcessing Statistics:", statsHeader));

            com.lowagie.text.List statsList = new com.lowagie.text.List(true, 15);
            statsList.add(new ListItem("Original Word Count: " + originalWords));
            statsList.add(new ListItem("Summary Word Count: " + summaryWords));
            statsList.add(new ListItem("Compression Efficiency: " + compression + "%"));
            document.add(statsList);

            // 4. The Summary
            Font summaryHeader = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, Color.BLACK);
            document.add(new Paragraph("\nAI Generated Summary:", summaryHeader));

            Font bodyFont = FontFactory.getFont(FontFactory.COURIER, 11, Color.BLACK);
            Paragraph summaryText = new Paragraph(summary, bodyFont);
            summaryText.setSpacingBefore(10);
            document.add(summaryText);

            // 5. Footer
            Font footerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 10, Color.GRAY);
            Paragraph footer = new Paragraph("\n\nGenerated by ADRP System - Automated Document & Report Processing", footerFont);
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            return out.toByteArray();

        } catch (IOException e) {
            e.printStackTrace();
            return null;
        }
    }
}